# Generated by Django 2.2.6 on 2019-11-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangodemo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpolyeeDetails',
            new_name='EmployeeData',
        ),
    ]
