# Generated by Django 2.2.6 on 2019-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangodemo', '0002_auto_20191118_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('eemail', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeData',
        ),
    ]
