# Generated by Django 2.2.6 on 2020-01-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0008_auto_20191227_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsDataInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=1000)),
                ('sectionname', models.CharField(max_length=1000)),
                ('controlname', models.CharField(max_length=1000)),
                ('securityquestion', models.CharField(max_length=1000)),
                ('response', models.CharField(max_length=1000)),
                ('additionalcomment', models.CharField(max_length=1000)),
                ('tagName', models.CharField(max_length=1000)),
                ('tagDescription', models.CharField(max_length=1000)),
                ('flag', models.IntegerField(default=1)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('userName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TagsInformation',
        ),
    ]
