# Generated by Django 2.2.6 on 2019-12-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0002_auto_20191125_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=1000)),
                ('sectionname', models.CharField(max_length=1000)),
                ('controlname', models.CharField(max_length=1000)),
                ('securityquestion', models.CharField(max_length=1000)),
                ('response', models.CharField(max_length=1000)),
                ('additionalcomment', models.CharField(max_length=1000)),
            ],
        ),
    ]
