# Generated by Django 2.2.6 on 2019-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0007_auto_20191223_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagsinformation',
            name='userName',
        ),
        migrations.AddField(
            model_name='tagsinformation',
            name='flag',
            field=models.IntegerField(default=1),
        ),
    ]
