# Generated by Django 2.2.7 on 2020-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0009_admindb_questiondb'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondb',
            name='exactmatch',
            field=models.IntegerField(default=0),
        ),
    ]
