# Generated by Django 3.0 on 2020-02-17 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0008_image_relevantresponsedatabase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('receivedDate', models.DateTimeField(null=True)),
                ('submittedDate', models.DateTimeField(null=True)),
                ('googleSheetLink', models.CharField(max_length=200, null=True)),
                ('documentLink', models.CharField(max_length=200, null=True)),
                ('relatedCommunication', models.TextField(null=True)),
                ('fileName', models.CharField(max_length=100)),
                ('clientId', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('additionalComment', models.TextField()),
                ('assignTo', models.CharField(blank=True, max_length=100)),
                ('assignBy', models.CharField(blank=True, max_length=100)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaireApp.AdminDB')),
            ],
        ),
    ]
