# Generated by Django 3.0 on 2020-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0007_auto_20200205_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorName', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('receivedDate', models.DateTimeField(auto_now_add=True)),
                ('submittedDate', models.DateTimeField()),
                ('googleSheetLink', models.CharField(max_length=200)),
                ('documentLink', models.CharField(max_length=200)),
                ('relatedCommunication', models.TextField()),
                ('fileName', models.CharField(max_length=100)),
                ('clientId', models.CharField(max_length=100)),
            ],
        ),
    ]
