# Generated by Django 3.0 on 2020-02-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0012_auto_20200213_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='receivedDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='admindb',
            name='submittedDate',
            field=models.DateField(null=True),
        ),
    ]
