# Generated by Django 3.0 on 2020-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0013_auto_20200213_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='receivedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='admindb',
            name='submittedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
