# Generated by Django 2.2.6 on 2020-02-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0010_questiondb_exactmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondb',
            name='additionalComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiondb',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questiondb',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
