# Generated by Django 2.2.6 on 2020-03-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0011_auto_20200224_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondb',
            name='assignBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questiondb',
            name='assignTo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
