# Generated by Django 2.2.7 on 2020-01-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0006_auto_20200122_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelevantResponseDatabase',
            new_name='RelevantResponseDatabase1',
        ),
        migrations.RenameField(
            model_name='relevantresponsedatabase1',
            old_name='userKeyword',
            new_name='userList',
        ),
    ]
