# Generated by Django 2.2.7 on 2020-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0007_auto_20200127_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelevantResponseDatabase2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userKeyword', models.CharField(max_length=60)),
                ('count', models.IntegerField()),
                ('keywordSearched', models.CharField(max_length=30)),
                ('userList', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='RelevantResponseDatabase1',
        ),
    ]
