# Generated by Django 2.2.6 on 2020-02-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0007_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
