# Generated by Django 2.2.7 on 2020-02-10 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0006_auto_20200122_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('noOfRows', models.IntegerField()),
                ('uploadedBy', models.CharField(max_length=100)),
                ('updatedBy', models.CharField(max_length=100)),
                ('uploadedTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSearchedDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MostFavouredResponseHistoryDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('vendorName', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('additionalComment', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserSessionDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('login', models.DateTimeField(auto_now_add=True)),
                ('logout', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tagwithinfo',
            old_name='userName',
            new_name='createdBy',
        ),
        migrations.AddField(
            model_name='tagwithinfo',
            name='destroyedBY',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagwithinfo',
            name='updatedBy',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
