# Generated by Django 3.0 on 2020-02-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0008_admindb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='documentLink',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admindb',
            name='googleSheetLink',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admindb',
            name='receivedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='admindb',
            name='relatedCommunication',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='admindb',
            name='submittedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
