# Generated by Django 3.0 on 2020-02-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0010_admindb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindb',
            name='status',
            field=models.IntegerField(),
        ),
    ]
