# Generated by Django 2.2.6 on 2019-12-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0004_auto_20191213_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(max_length=1000)),
                ('sectionname', models.CharField(max_length=1000)),
                ('controlname', models.CharField(max_length=1000)),
                ('securityquestion', models.CharField(max_length=1000)),
                ('response', models.CharField(max_length=1000)),
                ('additionalcomment', models.CharField(max_length=1000)),
                ('tagName', models.CharField(max_length=1000)),
                ('tagDescription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionnaireTags',
        ),
    ]
